// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBRVfbrk-oyHuWsw_wpWoHrDAFBg6P4hXE',
    appId: '1:882677499312:web:7823a22ce63bcf7aad0275',
    messagingSenderId: '882677499312',
    projectId: 'realtime-7f099',
    authDomain: 'realtime-7f099.firebaseapp.com',
    storageBucket: 'realtime-7f099.firebasestorage.app',
    measurementId: 'G-PEQ5PMR3VS',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDyD5srBlUysqFGzDUDtGGHbIycdy3BogI',
    appId: '1:882677499312:android:c623c847857440b4ad0275',
    messagingSenderId: '882677499312',
    projectId: 'realtime-7f099',
    storageBucket: 'realtime-7f099.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD1pOewgl_IKRlOxKUP9nbybS3j9wkEDl0',
    appId: '1:1096585580375:ios:47fa52d1edb845f972b812',
    messagingSenderId: '1096585580375',
    projectId: 'flutterfirebaseauth-439e4',
    storageBucket: 'flutterfirebaseauth-439e4.appspot.com',
    iosBundleId: 'com.example.otpFlutter',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBRVfbrk-oyHuWsw_wpWoHrDAFBg6P4hXE',
    appId: '1:882677499312:web:d85e88e2ad06016dad0275',
    messagingSenderId: '882677499312',
    projectId: 'realtime-7f099',
    authDomain: 'realtime-7f099.firebaseapp.com',
    storageBucket: 'realtime-7f099.firebasestorage.app',
    measurementId: 'G-4Q9DF1T9NQ',
  );

}